//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bagage.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Bagage
{
	public Object BagageNr;
	public Object TicketNr;
	public Object Gewicht;
}
