//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BagagePersoneel.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class BagagePersoneel extends Personeel
{
}
