//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Betaling.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Betaling
{
	public void Betalen()
	{
	}
}
