//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Checkin personeel.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Checkin personeel extends Personeel
{
}
