//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Maatschapij.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Maatschapij
{
	public Object private string NaamMaatschapij;
}
