//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Passagier.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Passagier
{
	public Object public bool heeftBagage;
	public Object public bool isIngechecket;
	public Object publick string Naam;
	public void Checkin()
	{
	}
	
	public void CheckinBagage()
	{
	}
	
	public void Boarden()
	{
	}
}
