//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Personeel.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Personeel
{
	public void ControleerTicket()
	{
	}
	
	public void LaadBagage()
	{
	}
}
