//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Stewardes.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Stewardes extends Personeel
{
}
