//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ticket.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Ticket
{
	public Object publick int TicketNr;
	public Object public int VluchtNr;
	public Object public bool isBetaald;
	public Object string Klasse;
	public Object public float prijs;
}
