//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vliegtuig.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Vliegtuig
{
	public Object private int Bagage[];
	public void Vlieg()
	{
	}
}
