//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vluchtdetails.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Vluchtdetails
{
	public Object Locatie Herkomst;
	public Object Locatie Besteming;
	public Object public int VluchtNr;
	public Object public int uurVertrek;
	public Object public int uurAankomst;
	public Object private string Piloot;
	public Object private int VliegtuigNr;
	public void ToonDetails()
	{
	}
}
