//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Vlucht.java
//  @ Date : 28/10/2016
//  @ Author : 
//
//




public class Vlucht
{
	public Object private List #passagiers;
	public Object private List VluchtNr;
	public Object private List BagageNr;
	public void IsComplete()
	{
	}
}
